<template>
  <Layout :title="$page.project.title">
    <article class="project-post">
      <g-image
        class="thumnail"
        :src="$page.project.thumbnail"
        :alt="$page.project.title"
      />
      <ProjectMeta
        :title="$page.project.title"
        :categories="$page.project.categories"
        :year="$page.project.year"
      />
      <div class="content" v-html="$page.project.content" />
    </article>
  </Layout>
</template>

<page-query>
query Project ($path: String!) {
  project: project(path: $path) {
    title
    thumbnail
    year
    categories
    content
  }
}
</page-query>

<script>
import ProjectMeta from "@/components/ProjectMeta";

export default {
  components: {
    ProjectMeta
  },
  mounted() {
    // Instead of checking for firstChild nodes that is text elements,
    // check and see if the p tags only contains img elements and that noscript
    // generated by Gridsome.
    const contentElements = document.querySelectorAll("p");
    contentElements.forEach(
      element =>
        element.firstChild.nodeName === "#text" &&
        element.classList.add("content-text")
    );
  }
};
</script>

<style lang="scss">
.project-post {
  padding: 0 2rem;
  margin-bottom: 8rem;
}

.project-title {
  text-align: left;
}

img{
  margin: auto;
  display:block;
  width:100%;
}
// img {
//   width: 94%;
//   margin-left: 3%;
//   margin-right: 3%;
//   // margin-bottom: 2rem;
// }
p {
  margin: 1rem;
}

h2 {
  text-align:center;
}

time {
  font-size:1.3rem;
}
.content-text, a {
  padding: 1rem 1rem 1rem 0;
  font-size: 1.3rem;
  font-weight: 400;
  margin:auto;
  max-width: 780px;
  line-height: 1.5;
}

iframe {
  display: block;
  margin: 0 auto;
}

article.project-post {
  padding-bottom: 9rem;
}

@media only screen and (max-width: 1000px) {
  .content-text {
    font-size: 1rem;
  }
}

//desktop images
@media only screen and (min-width: 800px) {
  div.content img {
    margin-left: 25%;
    margin-right: 25%;
    width: 50%;
  }

  article.project-post {
    width:75%;
    margin: auto;
  }
}
</style>